In [1]:
import numpy as np

In [2]:
my_array = np.arange(25).reshape(5, 5)

In [3]:
print(my_array)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [ ]:
#This code uses np.arange(25) to create an array of integers from 0 to 24, 
#and then reshape(5, 5) is used to reshape this 1D array into a 5x5 array.